Reach-OctreeWithColor-Gazebo-v0:
  policy: "OctreeCnnPolicy"
  policy_kwargs:
    features_extractor_kwargs:
      depth: 4
      full_depth: 2
      channels_in: 7
      channel_multiplier: 16
      full_depth_channels: 4
      features_dim: 128
      fast_conv: True
      batch_normalization: True
    n_quantiles: 25
    net_arch: [256, 128]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        robot_random_joint_positions: False
        camera_pose_rollouts_num: 0
        object_random_pose: True
        camera_noise_mean: 0
        camera_noise_stddev: 0.001
  n_timesteps: 100000
  buffer_size: 50000
  learning_starts: 5000
  batch_size: 32
  learning_rate: lin_0.0001
  gamma: 0.99
  tau: 0.005
  ent_coef: "auto_0.5_0.025"
  target_entropy: "auto"
  top_quantiles_to_drop_per_net: 2
  train_freq: 1
  gradient_steps: 2
  noise_type: "normal"
  noise_std: 0.025
  optimize_memory_usage: True

Grasp-Octree-Gazebo-v0:
  policy: "OctreeCnnPolicy"
  policy_kwargs:
    features_extractor_kwargs:
      depth: 5
      full_depth: 2
      channels_in: 4
      channel_multiplier: 16
      full_depth_conv1d: True
      full_depth_channels: 16
      features_dim: 128
      aux_obs_dim: 10
      fast_conv: True
      batch_normalization: True
    n_quantiles: 20
    net_arch: [256, 256]
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        robot_random_joint_positions: False
        camera_pose_rollouts_num: 0
        ground_model_rollouts_num: 0
        object_random_pose: True
        object_random_use_mesh_models: False
        object_models_rollouts_num: 1
        object_random_model_count: 1
        camera_noise_mean: 0
        camera_noise_stddev: 0.001
  n_timesteps: 1000000
  buffer_size: 25000
  learning_starts: 5000
  batch_size: 32
  learning_rate: lin_0.0002
  gamma: 0.99
  tau: 0.01
  ent_coef: "auto_0.1_0.05"
  target_entropy: "auto"
  top_quantiles_to_drop_per_net: 2
  train_freq: 1
  gradient_steps: 1
  noise_type: "normal"
  noise_std: 0.025
  optimize_memory_usage: True

# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 5
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 4
#       full_depth_conv1d: False
#       full_depth_channels: 2
#       features_dim: 28
#       aux_obs_dim: 10
#       fast_conv: True
#       batch_normalization: True
#     n_quantiles: 20
#     net_arch: [128, 128]
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: False
#         camera_pose_rollouts_num: 0
#         ground_model_rollouts_num: 0
#         object_random_pose: True
#         object_random_use_mesh_models: False
#         object_models_rollouts_num: 1
#         object_random_model_count: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#   n_timesteps: 30000
#   buffer_size: 30000
#   learning_starts: 0
#   batch_size: 32
#   learning_rate: lin_0.001
#   gamma: 0.99
#   tau: 0.001
#   ent_coef: "auto_0.5_0.05"
#   target_entropy: "auto"
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 4
#   noise_type: "normal"
#   noise_std: 0.025
#   optimize_memory_usage: True

# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 5
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 4
#       full_depth_conv1d: False
#       full_depth_channels: 2
#       features_dim: 28
#       aux_obs_dim: 10
#       fast_conv: True
#       batch_normalization: True
#     n_quantiles: 20
#     net_arch: [128, 128]
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: False
#         camera_pose_rollouts_num: 0
#         ground_model_rollouts_num: 0
#         object_random_pose: True
#         object_random_use_mesh_models: False
#         object_models_rollouts_num: 1
#         object_random_model_count: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#   n_timesteps: 30000
#   buffer_size: 30000
#   learning_starts: 0
#   batch_size: 32
#   learning_rate: lin_0.001
#   gamma: 0.99
#   tau: 0.001
#   ent_coef: "auto_0.5_0.05"
#   target_entropy: "auto"
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 4
#   noise_type: "normal"
#   noise_std: 0.025
#   optimize_memory_usage: True

# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 4
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 8
#       full_depth_conv1d: True
#       full_depth_channels: 16
#       features_dim: 118
#       aux_obs_dim: 10
#       fast_conv: True
#       batch_normalization: True
#       bn_eps: 0.00001
#       bn_momentum: 0.01
#     n_quantiles: 25
#     net_arch: [256, 256]
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: True
#         robot_random_joint_positions_std: 0.1
#         camera_pose_rollouts_num: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#         ground_model_rollouts_num: 1
#         object_random_pose: True
#         object_random_use_mesh_models: True
#         object_models_rollouts_num: 1
#         # This param will be ignored if curriculum is set to automatically determine the number of objects in the scene
#         object_random_model_count: 1
#   normalize: "{'norm_obs': False, 'norm_reward': True, 'clip_reward': 100.0}"
#   n_timesteps: 1000000
#   buffer_size: 30000
#   learning_starts: 5000
#   batch_size: 32
#   learning_rate: lin_0.00025
#   gamma: 0.99
#   tau: 0.01
#   ent_coef: "auto_0.1_0.05"
#   target_entropy: "auto"
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 1
#   noise_type: "normal"
#   noise_std: 0.05
#   optimize_memory_usage: True

# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 4
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 8
#       full_depth_conv1d: True
#       full_depth_channels: 16
#       features_dim: 118
#       aux_obs_dim: 10
#       fast_conv: True
#       batch_normalization: True
#       bn_eps: 0.00001
#       bn_momentum: 0.01
#     n_quantiles: 25
#     net_arch: [256, 256]
#     share_features_extractor: False
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: True
#         robot_random_joint_positions_std: 0.1
#         camera_pose_rollouts_num: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#         ground_model_rollouts_num: 1
#         object_random_pose: True
#         object_random_use_mesh_models: True
#         object_models_rollouts_num: 1
#         # This param will be ignored if curriculum is set to automatically determine the number of objects in the scene
#         object_random_model_count: 1
#   normalize: "{'norm_obs': False, 'norm_reward': True}"
#   n_timesteps: 1000000
#   buffer_size: 25000
#   learning_starts: 0
#   batch_size: 32
#   learning_rate: lin_0.0001
#   gamma: 0.99
#   tau: 0.01
#   ent_coef: "auto_0.1_0.05"
#   target_entropy: "auto"
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 2
#   noise_type: "normal"
#   noise_std: 0.025
#   optimize_memory_usage: True

# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 4
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 32
#       full_depth_conv1d: True
#       full_depth_channels: 16
#       features_dim: 128
#       aux_obs_dim: 10
#       fast_conv: True
#       batch_normalization: False
#       bn_eps: 0.00001
#       bn_momentum: 0.01
#     n_quantiles: 25
#     n_critics: 3
#     net_arch: [256, 256]
#     share_features_extractor: True
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: True
#         robot_random_joint_positions_std: 0.1
#         camera_pose_rollouts_num: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#         ground_model_rollouts_num: 1
#         object_random_pose: True
#         object_random_use_mesh_models: True
#         object_models_rollouts_num: 1
#         # This param will be ignored if curriculum is set to automatically determine the number of objects in the scene
#         object_random_model_count: 1
#   # normalize: "{'norm_obs': False, 'norm_reward': True}"
#   n_timesteps: 2000000
#   buffer_size: 25000
#   learning_starts: 0
#   batch_size: 64
#   learning_rate: lin_0.0002
#   gamma: 0.999
#   tau: 0.0005
#   # ent_coef: "auto_0.1_0.05"
#   ent_coef: 0.0025
#   target_entropy: "auto"
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 2
#   noise_type: "normal"
#   noise_std: 0.02
#   optimize_memory_usage: True



# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 4
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 4
#       full_depth_conv1d: True
#       full_depth_channels: 4
#       features_dim: 64
#       aux_obs_dim: 10
#       fast_conv: True
#       batch_normalization: False
#       bn_eps: 0.00001
#       bn_momentum: 0.01
#     n_quantiles: 25
#     n_critics: 3
#     net_arch: [256, 256]
#     share_features_extractor: True
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: True
#         robot_random_joint_positions_std: 0.1
#         camera_pose_rollouts_num: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#         ground_model_rollouts_num: 1
#         object_random_pose: True
#         object_random_use_mesh_models: True
#         object_models_rollouts_num: 1
#         # This param will be ignored if curriculum is set to automatically determine the number of objects in the scene
#         object_random_model_count: 1
#   normalize: "{'norm_obs': False, 'norm_reward': True}"
#   n_timesteps: 2000000
#   buffer_size: 25000
#   learning_starts: 0
#   batch_size: 64
#   learning_rate: lin_0.0002
#   gamma: 0.999
#   tau: 0.0005
#   ent_coef: "auto_0.1_0.05"
#   # ent_coef: 0.0005
#   # target_entropy: "auto"
#   target_entropy: 0.001
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 2
#   noise_type: "normal"
#   noise_std: 0.025
#   optimize_memory_usage: True




# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 4
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 16
#       full_depth_conv1d: True
#       full_depth_channels: 4
#       features_dim: 64
#       aux_obs_dim: 10
#       fast_conv: True
#       batch_normalization: False
#       bn_eps: 0.00001
#       bn_momentum: 0.01
#     n_quantiles: 25
#     n_critics: 2
#     net_arch: [386, 386]
#     share_features_extractor: True
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: True
#         robot_random_joint_positions_std: 0.1
#         camera_pose_rollouts_num: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#         ground_model_rollouts_num: 1
#         object_random_pose: True
#         object_random_use_mesh_models: True
#         object_models_rollouts_num: 1
#         # This param will be ignored if curriculum is set to automatically determine the number of objects in the scene
#         object_random_model_count: 1
#   normalize: "{'norm_obs': False, 'norm_reward': True}"
#   n_timesteps: 500000
#   buffer_size: 25000
#   learning_starts: 0
#   batch_size: 96
#   learning_rate: lin_0.0025
#   gamma: 0.999
#   tau: 0.001
#   ent_coef: "auto_0.1_0.05"
#   # ent_coef: 0.0005
#   target_entropy: "auto"
#   # target_entropy: -10.0
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 1
#   noise_type: "normal"
#   noise_std: 0.025
#   optimize_memory_usage: True


# Grasp-OctreeWithColor-Gazebo-v0:
#   policy: "OctreeCnnPolicy"
#   policy_kwargs:
#     features_extractor_kwargs:
#       depth: 4
#       full_depth: 2
#       channels_in: 7
#       channel_multiplier: 16
#       full_depth_conv1d: True
#       full_depth_channels: 4
#       features_dim: 96
#       aux_obs_dim: 0
#       fast_conv: True
#       batch_normalization: False
#       bn_eps: 0.00001
#       bn_momentum: 0.01
#     n_quantiles: 25
#     n_critics: 3
#     net_arch: [386, 386]
#     share_features_extractor: True
#   env_wrapper:
#     - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
#         robot_random_joint_positions: True
#         robot_random_joint_positions_std: 0.1
#         camera_pose_rollouts_num: 1
#         camera_noise_mean: 0
#         camera_noise_stddev: 0.001
#         ground_model_rollouts_num: 1
#         object_random_pose: True
#         object_random_use_mesh_models: True
#         object_models_rollouts_num: 1
#         # This param will be ignored if curriculum is set to automatically determine the number of objects in the scene
#         object_random_model_count: 1
#   normalize: "{'norm_obs': False, 'norm_reward': True}"
#   n_timesteps: 500000
#   buffer_size: 25000
#   learning_starts: 0
#   batch_size: 64
#   learning_rate: lin_0.000025
#   gamma: 0.999
#   tau: 0.00005
#   ent_coef: "auto_0.1_0.05"
#   # ent_coef: 0.0005
#   target_entropy: "auto"
#   # target_entropy: -10.0
#   top_quantiles_to_drop_per_net: 2
#   train_freq: 1
#   gradient_steps: 1
#   noise_type: "normal"
#   noise_std: 0.025
#   # robotlab - True
#   optimize_memory_usage: False



Grasp-OctreeWithColor-Gazebo-v0:
  policy: "OctreeCnnPolicy"
  policy_kwargs:
    features_extractor_kwargs:
      depth: 4
      full_depth: 2
      channels_in: 7
      channel_multiplier: 48
      full_depth_conv1d: False
      full_depth_channels: 16
      features_dim: 256
      aux_obs_dim: 10
      fast_conv: True
      batch_normalization: False
      bn_eps: 0.00001
      bn_momentum: 0.01
    n_quantiles: 25
    n_critics: 3
    net_arch: [512, 512]
    share_features_extractor: True
  env_wrapper:
    - drl_grasping.envs.randomizers.ManipulationGazeboEnvRandomizer:
        robot_random_joint_positions: True
        robot_random_joint_positions_std: 0.1
        camera_pose_rollouts_num: 1
        camera_noise_mean: 0
        camera_noise_stddev: 0.001
        ground_model_rollouts_num: 1
        object_random_pose: True
        object_random_use_mesh_models: True
        object_models_rollouts_num: 1
        # This param will be ignored if curriculum is set to automatically determine the number of objects in the scene
        object_random_model_count: 1
  normalize: "{'norm_obs': False, 'norm_reward': True}"
  n_timesteps: 500000
  buffer_size: 25000
  learning_starts: 0
  batch_size: 32
  learning_rate: lin_0.0000005
  gamma: 0.999
  tau: 0.000025
  ent_coef: "auto_0.1_0.05"
  target_entropy: "auto"
  top_quantiles_to_drop_per_net: 2
  train_freq: 1
  gradient_steps: 1
  noise_type: "normal"
  noise_std: 0.1
  optimize_memory_usage: True
